import React, { useState, useEffect } from "react";
import { Link, useNavigate, useLocation } from "react-router-dom";
import { ArrowLeft, AlertCircle, ShieldCheck } from "lucide-react";
import AuthLayout from "../../../components/auth/AuthLayout";
import AuthInput from "../../../components/auth/AuthInput";
import PasswordInput from "../../../components/auth/PasswordInput";
import OtpInput from "../../../components/common/OtpInput/OtpInput";
import useAuth from "../../../hooks/useAuth";
import "./Login.css";

const Login = () => {
  const { login, verifyLoginMfa } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();

  const [formData, setFormData] = useState({
    email: location.state?.registeredEmail || "",
    password: "",
    rememberMe: false,
  });

  const [fieldErrors, setFieldErrors] = useState({});
  const [globalError, setGlobalError] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);

  // MFA 2FA State
  const [mfaRequired, setMfaRequired] = useState(false);
  const [mfaUserId, setMfaUserId] = useState(null);
  const [totpCode, setTotpCode] = useState("");

  useEffect(() => {
    if (location.state?.registeredEmail) {
      setFormData((prev) => ({ ...prev, email: location.state.registeredEmail }));
    }
  }, [location.state]);

  const from = location.state?.from?.pathname || "/dashboard";

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: type === "checkbox" ? checked : value,
    }));

    if (fieldErrors[name]) {
      setFieldErrors((prev) => ({ ...prev, [name]: "" }));
    }
    if (globalError) {
      setGlobalError("");
    }
  };

  const validateForm = () => {
    const errors = {};
    if (!formData.email || !formData.email.trim()) {
      errors.email = "Please enter your email address.";
    }

    if (!formData.password || !formData.password.trim()) {
      errors.password = "Please enter your password.";
    }

    setFieldErrors(errors);
    return Object.keys(errors).length === 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setGlobalError("");

    if (!validateForm()) {
      return;
    }

    setIsSubmitting(true);
    try {
      const result = await login(formData.email.trim(), formData.password, formData.rememberMe);
      if (result && result.mfaRequired) {
        setMfaRequired(true);
        setMfaUserId(result.userId);
        setIsSubmitting(false);
        return;
      }
      navigate(from, { replace: true });
    } catch (err) {
      if (err.errors && Array.isArray(err.errors)) {
        const errorsObj = {};
        err.errors.forEach((item) => {
          if (item.field) errorsObj[item.field] = item.message;
        });
        setFieldErrors(errorsObj);
      } else {
        setGlobalError(err.message || "Invalid email or password.");
      }
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleMfaSubmit = async (e) => {
    e.preventDefault();
    setGlobalError("");

    const cleanCode = totpCode.trim();
    if (!cleanCode || cleanCode.length !== 6 || isNaN(cleanCode)) {
      setGlobalError("Please enter a valid 6-digit passcode from your Authenticator app.");
      return;
    }

    setIsSubmitting(true);
    try {
      await verifyLoginMfa(mfaUserId, cleanCode);
      navigate(from, { replace: true });
    } catch (err) {
      setGlobalError(err.message || "Invalid authentication passcode. Please try again.");
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleCancelMfa = () => {
    setMfaRequired(false);
    setMfaUserId(null);
    setTotpCode("");
    setGlobalError("");
  };

  return (
    <AuthLayout>
      <div className="auth-header">
        <Link to="/" className="auth-card-back-link">
          <ArrowLeft size={16} />
          <span>Back to Home Page</span>
        </Link>
        <h2 className="auth-title">{mfaRequired ? "Two-Factor Verification" : "Welcome Back"}</h2>
        <p className="auth-subtitle">
          {mfaRequired
            ? "Enter the 6-digit code generated by your Authenticator app"
            : "Sign in to access your CRM"}
        </p>
      </div>

      {globalError && (
        <div className="auth-alert auth-alert-error">
          <AlertCircle size={18} />
          <span>{globalError}</span>
        </div>
      )}

      {mfaRequired ? (
        <form className="auth-form" onSubmit={handleMfaSubmit} noValidate>
          <div style={{ display: "flex", justifyContent: "center", marginBottom: "0.5rem" }}>
            <div
              style={{
                background: "rgba(139, 35, 29, 0.08)",
                padding: "14px",
                borderRadius: "50%",
                color: "#8B231D",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              <ShieldCheck size={36} />
            </div>
          </div>

          <div style={{ textAlign: "center", marginBottom: "0.25rem" }}>
            <label
              style={{
                fontSize: "0.875rem",
                fontWeight: "600",
                color: "#25282A",
                display: "block",
                marginBottom: "0.5rem",
              }}
            >
              Enter 6-Digit Authenticator Code
            </label>

            <OtpInput
              value={totpCode}
              onChange={(val) => {
                setTotpCode(val);
                if (globalError) setGlobalError("");
              }}
              disabled={isSubmitting}
              autoFocus
            />
          </div>

          <button type="submit" className="btn-submit" disabled={isSubmitting || totpCode.length !== 6}>
            {isSubmitting ? "Verifying Code..." : "Verify & Sign In"}
          </button>

          <button
            type="button"
            className="btn-cancel-mfa"
            onClick={handleCancelMfa}
            disabled={isSubmitting}
            style={{
              marginTop: "6px",
              background: "transparent",
              border: "none",
              color: "#596067",
              cursor: "pointer",
              fontSize: "0.875rem",
              fontWeight: "500",
              padding: "8px",
              textAlign: "center",
              width: "100%",
              transition: "color 0.2s ease",
            }}
            onMouseEnter={(e) => (e.currentTarget.style.color = "#8B231D")}
            onMouseLeave={(e) => (e.currentTarget.style.color = "#596067")}
          >
            ← Cancel and Return to Sign In
          </button>
        </form>
      ) : (
        <form className="auth-form" onSubmit={handleSubmit} noValidate>
          <AuthInput
            label="Email Address"
            name="email"
            type="email"
            value={formData.email}
            onChange={handleChange}
            placeholder="Enter your email (e.g. admin@gmail.com)"
            error={fieldErrors.email}
            disabled={isSubmitting}
            required
          />

          <PasswordInput
            label="Password"
            name="password"
            value={formData.password}
            onChange={handleChange}
            placeholder="••••••••"
            error={fieldErrors.password}
            disabled={isSubmitting}
            required
          />

          <div className="auth-form-options">
            <label className="checkbox-label">
              <input
                type="checkbox"
                name="rememberMe"
                checked={formData.rememberMe}
                onChange={handleChange}
                disabled={isSubmitting}
              />
              <span>Remember me</span>
            </label>

            <Link to="/forgot-password" className="forgot-password-link">
              Forgot Password?
            </Link>
          </div>

          <button type="submit" className="btn-submit" disabled={isSubmitting}>
            {isSubmitting ? "Signing In..." : "Sign In"}
          </button>
        </form>
      )}
    </AuthLayout>
  );
};

export default Login;
